services:
  - type: web
    name: literary-bot
    env: python
    plan: free
    region: frankfurt
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: GIGACHAT_CREDENTIALS
        sync: false
        optional: true
    autoDeploy: true
